const request = require("./utils").request;

exports.handler = async function (event, context) {
	let query = new URLSearchParams(event.body).get("query");
	let resp = await request(`http://api.weatherapi.com/v1/forecast.json?q=${query}&key=13241e17ba4045aa99440133212110`, {})
	return {
		statusCode: 200,
		body: JSON.stringify(resp)
	}


	// this return statement contains the weather data taken at 11AM on 8th November 2021. 
	// This data was used for testing so as to not exhaust the API calls.
	// To use this, simply comment line 7-11.
	return {
		statusCode: 200,
		body: JSON.stringify(
			{
				"location": {
					"name": "Chandigarh",
					"region": "",
					"country": "India",
					"lat": 30.74,
					"lon": 76.79,
					"tz_id": "Asia/Kolkata",
					"localtime_epoch": 1636348968,
					"localtime": "2021-11-08 10:52"
				},
				"current": {
					"last_updated_epoch": 1636348500,
					"last_updated": "2021-11-08 10:45",
					"temp_c": 23.3,
					"temp_f": 73.9,
					"is_day": 1,
					"condition": {
						"text": "Sunny",
						"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
						"code": 1000
					},
					"wind_mph": 2.2,
					"wind_kph": 3.6,
					"wind_degree": 244,
					"wind_dir": "WSW",
					"pressure_mb": 1015,
					"pressure_in": 29.98,
					"precip_mm": 0,
					"precip_in": 0,
					"humidity": 27,
					"cloud": 0,
					"feelslike_c": 23.6,
					"feelslike_f": 74.5,
					"vis_km": 10,
					"vis_miles": 6,
					"uv": 6,
					"gust_mph": 2.5,
					"gust_kph": 4
				},
				"forecast": {
					"forecastday": [
						{
							"date": "2021-11-08",
							"date_epoch": 1636329600,
							"day": {
								"maxtemp_c": 32.3,
								"maxtemp_f": 90.1,
								"mintemp_c": 15.9,
								"mintemp_f": 60.6,
								"avgtemp_c": 22.4,
								"avgtemp_f": 72.3,
								"maxwind_mph": 14.8,
								"maxwind_kph": 23.8,
								"totalprecip_mm": 0,
								"totalprecip_in": 0,
								"avgvis_km": 10,
								"avgvis_miles": 6,
								"avghumidity": 32,
								"daily_will_it_rain": 0,
								"daily_chance_of_rain": 0,
								"daily_will_it_snow": 0,
								"daily_chance_of_snow": 0,
								"condition": {
									"text": "Sunny",
									"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
									"code": 1000
								},
								"uv": 5
							},
							"astro": {
								"sunrise": "06:43 AM",
								"sunset": "05:30 PM",
								"moonrise": "10:31 AM",
								"moonset": "08:40 PM",
								"moon_phase": "First Quarter",
								"moon_illumination": "34"
							},
							"hour": [
								{
									"time_epoch": 1636309800,
									"time": "2021-11-08 00:00",
									"temp_c": 17.9,
									"temp_f": 64.2,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 5.4,
									"wind_kph": 8.6,
									"wind_degree": 31,
									"wind_dir": "NNE",
									"pressure_mb": 1014,
									"pressure_in": 29.94,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 40,
									"cloud": 0,
									"feelslike_c": 17.9,
									"feelslike_f": 64.2,
									"windchill_c": 17.9,
									"windchill_f": 64.2,
									"heatindex_c": 17.9,
									"heatindex_f": 64.2,
									"dewpoint_c": 4.2,
									"dewpoint_f": 39.6,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 11.2,
									"gust_kph": 18,
									"uv": 1
								},
								{
									"time_epoch": 1636313400,
									"time": "2021-11-08 01:00",
									"temp_c": 17.6,
									"temp_f": 63.7,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 4.9,
									"wind_kph": 7.9,
									"wind_degree": 32,
									"wind_dir": "NNE",
									"pressure_mb": 1014,
									"pressure_in": 29.93,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 40,
									"cloud": 0,
									"feelslike_c": 17.6,
									"feelslike_f": 63.7,
									"windchill_c": 17.6,
									"windchill_f": 63.7,
									"heatindex_c": 17.6,
									"heatindex_f": 63.7,
									"dewpoint_c": 4,
									"dewpoint_f": 39.2,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 10.3,
									"gust_kph": 16.6,
									"uv": 1
								},
								{
									"time_epoch": 1636317000,
									"time": "2021-11-08 02:00",
									"temp_c": 17.2,
									"temp_f": 63,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 4.3,
									"wind_kph": 6.8,
									"wind_degree": 42,
									"wind_dir": "NE",
									"pressure_mb": 1014,
									"pressure_in": 29.94,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 41,
									"cloud": 0,
									"feelslike_c": 17.2,
									"feelslike_f": 63,
									"windchill_c": 17.2,
									"windchill_f": 63,
									"heatindex_c": 17.2,
									"heatindex_f": 63,
									"dewpoint_c": 3.7,
									"dewpoint_f": 38.7,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 8.9,
									"gust_kph": 14.4,
									"uv": 1
								},
								{
									"time_epoch": 1636320600,
									"time": "2021-11-08 03:00",
									"temp_c": 16.9,
									"temp_f": 62.4,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 4.5,
									"wind_kph": 7.2,
									"wind_degree": 35,
									"wind_dir": "NE",
									"pressure_mb": 1013,
									"pressure_in": 29.93,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 40,
									"cloud": 0,
									"feelslike_c": 16.9,
									"feelslike_f": 62.4,
									"windchill_c": 16.9,
									"windchill_f": 62.4,
									"heatindex_c": 16.9,
									"heatindex_f": 62.4,
									"dewpoint_c": 3.4,
									"dewpoint_f": 38.1,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 9.4,
									"gust_kph": 15.1,
									"uv": 1
								},
								{
									"time_epoch": 1636324200,
									"time": "2021-11-08 04:00",
									"temp_c": 16.6,
									"temp_f": 61.9,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 4.5,
									"wind_kph": 7.2,
									"wind_degree": 31,
									"wind_dir": "NNE",
									"pressure_mb": 1013,
									"pressure_in": 29.92,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 40,
									"cloud": 0,
									"feelslike_c": 16.6,
									"feelslike_f": 61.9,
									"windchill_c": 16.6,
									"windchill_f": 61.9,
									"heatindex_c": 16.6,
									"heatindex_f": 61.9,
									"dewpoint_c": 3.1,
									"dewpoint_f": 37.6,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 9.4,
									"gust_kph": 15.1,
									"uv": 1
								},
								{
									"time_epoch": 1636327800,
									"time": "2021-11-08 05:00",
									"temp_c": 16.3,
									"temp_f": 61.3,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 3.8,
									"wind_kph": 6.1,
									"wind_degree": 28,
									"wind_dir": "NNE",
									"pressure_mb": 1013,
									"pressure_in": 29.92,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 41,
									"cloud": 0,
									"feelslike_c": 16.3,
									"feelslike_f": 61.3,
									"windchill_c": 16.3,
									"windchill_f": 61.3,
									"heatindex_c": 16.3,
									"heatindex_f": 61.3,
									"dewpoint_c": 2.9,
									"dewpoint_f": 37.2,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 8.1,
									"gust_kph": 13,
									"uv": 1
								},
								{
									"time_epoch": 1636331400,
									"time": "2021-11-08 06:00",
									"temp_c": 15.9,
									"temp_f": 60.6,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 3.8,
									"wind_kph": 6.1,
									"wind_degree": 31,
									"wind_dir": "NNE",
									"pressure_mb": 1014,
									"pressure_in": 29.93,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 41,
									"cloud": 0,
									"feelslike_c": 15.9,
									"feelslike_f": 60.6,
									"windchill_c": 15.9,
									"windchill_f": 60.6,
									"heatindex_c": 15.9,
									"heatindex_f": 60.6,
									"dewpoint_c": 2.6,
									"dewpoint_f": 36.7,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 8.1,
									"gust_kph": 13,
									"uv": 1
								},
								{
									"time_epoch": 1636335000,
									"time": "2021-11-08 07:00",
									"temp_c": 16.8,
									"temp_f": 62.2,
									"is_day": 1,
									"condition": {
										"text": "Sunny",
										"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
										"code": 1000
									},
									"wind_mph": 3.6,
									"wind_kph": 5.8,
									"wind_degree": 31,
									"wind_dir": "NNE",
									"pressure_mb": 1014,
									"pressure_in": 29.95,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 40,
									"cloud": 0,
									"feelslike_c": 16.8,
									"feelslike_f": 62.2,
									"windchill_c": 16.8,
									"windchill_f": 62.2,
									"heatindex_c": 16.8,
									"heatindex_f": 62.2,
									"dewpoint_c": 3.1,
									"dewpoint_f": 37.6,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 7.6,
									"gust_kph": 12.2,
									"uv": 5
								},
								{
									"time_epoch": 1636338600,
									"time": "2021-11-08 08:00",
									"temp_c": 20.5,
									"temp_f": 68.9,
									"is_day": 1,
									"condition": {
										"text": "Sunny",
										"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
										"code": 1000
									},
									"wind_mph": 2,
									"wind_kph": 3.2,
									"wind_degree": 29,
									"wind_dir": "NNE",
									"pressure_mb": 1015,
									"pressure_in": 29.97,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 33,
									"cloud": 0,
									"feelslike_c": 20.5,
									"feelslike_f": 68.9,
									"windchill_c": 20.5,
									"windchill_f": 68.9,
									"heatindex_c": 20.5,
									"heatindex_f": 68.9,
									"dewpoint_c": 3.6,
									"dewpoint_f": 38.5,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 2.9,
									"gust_kph": 4.7,
									"uv": 6
								},
								{
									"time_epoch": 1636342200,
									"time": "2021-11-08 09:00",
									"temp_c": 23.3,
									"temp_f": 73.9,
									"is_day": 1,
									"condition": {
										"text": "Sunny",
										"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
										"code": 1000
									},
									"wind_mph": 2.2,
									"wind_kph": 3.6,
									"wind_degree": 244,
									"wind_dir": "WSW",
									"pressure_mb": 1015,
									"pressure_in": 29.98,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 27,
									"cloud": 0,
									"feelslike_c": 23.6,
									"feelslike_f": 74.5,
									"windchill_c": 23.3,
									"windchill_f": 73.9,
									"heatindex_c": 23.6,
									"heatindex_f": 74.5,
									"dewpoint_c": 3.5,
									"dewpoint_f": 38.3,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 2.5,
									"gust_kph": 4,
									"uv": 6
								},
								{
									"time_epoch": 1636345800,
									"time": "2021-11-08 10:00",
									"temp_c": 24.9,
									"temp_f": 76.8,
									"is_day": 1,
									"condition": {
										"text": "Sunny",
										"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
										"code": 1000
									},
									"wind_mph": 4.5,
									"wind_kph": 7.2,
									"wind_degree": 267,
									"wind_dir": "W",
									"pressure_mb": 1015,
									"pressure_in": 29.97,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 24,
									"cloud": 0,
									"feelslike_c": 24.2,
									"feelslike_f": 75.6,
									"windchill_c": 24.9,
									"windchill_f": 76.8,
									"heatindex_c": 24.2,
									"heatindex_f": 75.6,
									"dewpoint_c": 3.2,
									"dewpoint_f": 37.8,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 5.1,
									"gust_kph": 8.3,
									"uv": 6
								},
								{
									"time_epoch": 1636349400,
									"time": "2021-11-08 11:00",
									"temp_c": 30,
									"temp_f": 86,
									"is_day": 1,
									"condition": {
										"text": "Sunny",
										"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
										"code": 1000
									},
									"wind_mph": 7.4,
									"wind_kph": 11.9,
									"wind_degree": 291,
									"wind_dir": "WNW",
									"pressure_mb": 1014,
									"pressure_in": 29.94,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 20,
									"cloud": 0,
									"feelslike_c": 27.8,
									"feelslike_f": 82,
									"windchill_c": 30,
									"windchill_f": 86,
									"heatindex_c": 27.8,
									"heatindex_f": 82,
									"dewpoint_c": 4.9,
									"dewpoint_f": 40.8,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 8.5,
									"gust_kph": 13.7,
									"uv": 8
								},
								{
									"time_epoch": 1636353000,
									"time": "2021-11-08 12:00",
									"temp_c": 31.6,
									"temp_f": 88.9,
									"is_day": 1,
									"condition": {
										"text": "Sunny",
										"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
										"code": 1000
									},
									"wind_mph": 10.1,
									"wind_kph": 16.2,
									"wind_degree": 300,
									"wind_dir": "WNW",
									"pressure_mb": 1013,
									"pressure_in": 29.9,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 18,
									"cloud": 0,
									"feelslike_c": 29.4,
									"feelslike_f": 84.9,
									"windchill_c": 31.6,
									"windchill_f": 88.9,
									"heatindex_c": 29.4,
									"heatindex_f": 84.9,
									"dewpoint_c": 4.2,
									"dewpoint_f": 39.6,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 11.6,
									"gust_kph": 18.7,
									"uv": 8
								},
								{
									"time_epoch": 1636356600,
									"time": "2021-11-08 13:00",
									"temp_c": 32.2,
									"temp_f": 90,
									"is_day": 1,
									"condition": {
										"text": "Sunny",
										"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
										"code": 1000
									},
									"wind_mph": 12.3,
									"wind_kph": 19.8,
									"wind_degree": 302,
									"wind_dir": "WNW",
									"pressure_mb": 1012,
									"pressure_in": 29.87,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 16,
									"cloud": 0,
									"feelslike_c": 30,
									"feelslike_f": 86,
									"windchill_c": 32.2,
									"windchill_f": 90,
									"heatindex_c": 30,
									"heatindex_f": 86,
									"dewpoint_c": 3.6,
									"dewpoint_f": 38.5,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 14.1,
									"gust_kph": 22.7,
									"uv": 8
								},
								{
									"time_epoch": 1636360200,
									"time": "2021-11-08 14:00",
									"temp_c": 32.3,
									"temp_f": 90.1,
									"is_day": 1,
									"condition": {
										"text": "Sunny",
										"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
										"code": 1000
									},
									"wind_mph": 14.1,
									"wind_kph": 22.7,
									"wind_degree": 307,
									"wind_dir": "NW",
									"pressure_mb": 1011,
									"pressure_in": 29.86,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 16,
									"cloud": 0,
									"feelslike_c": 30.1,
									"feelslike_f": 86.2,
									"windchill_c": 32.3,
									"windchill_f": 90.1,
									"heatindex_c": 30.1,
									"heatindex_f": 86.2,
									"dewpoint_c": 3.3,
									"dewpoint_f": 37.9,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 16.1,
									"gust_kph": 25.9,
									"uv": 8
								},
								{
									"time_epoch": 1636363800,
									"time": "2021-11-08 15:00",
									"temp_c": 31.7,
									"temp_f": 89.1,
									"is_day": 1,
									"condition": {
										"text": "Sunny",
										"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
										"code": 1000
									},
									"wind_mph": 14.8,
									"wind_kph": 23.8,
									"wind_degree": 315,
									"wind_dir": "NW",
									"pressure_mb": 1011,
									"pressure_in": 29.85,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 17,
									"cloud": 0,
									"feelslike_c": 29.5,
									"feelslike_f": 85.1,
									"windchill_c": 31.7,
									"windchill_f": 89.1,
									"heatindex_c": 29.5,
									"heatindex_f": 85.1,
									"dewpoint_c": 3.7,
									"dewpoint_f": 38.7,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 17,
									"gust_kph": 27.4,
									"uv": 8
								},
								{
									"time_epoch": 1636367400,
									"time": "2021-11-08 16:00",
									"temp_c": 29.5,
									"temp_f": 85.1,
									"is_day": 1,
									"condition": {
										"text": "Sunny",
										"icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
										"code": 1000
									},
									"wind_mph": 12.3,
									"wind_kph": 19.8,
									"wind_degree": 318,
									"wind_dir": "NW",
									"pressure_mb": 1011,
									"pressure_in": 29.85,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 21,
									"cloud": 0,
									"feelslike_c": 27.4,
									"feelslike_f": 81.3,
									"windchill_c": 29.5,
									"windchill_f": 85.1,
									"heatindex_c": 27.4,
									"heatindex_f": 81.3,
									"dewpoint_c": 5,
									"dewpoint_f": 41,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 14.1,
									"gust_kph": 22.7,
									"uv": 7
								},
								{
									"time_epoch": 1636371000,
									"time": "2021-11-08 17:00",
									"temp_c": 26,
									"temp_f": 78.8,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 8.7,
									"wind_kph": 14,
									"wind_degree": 327,
									"wind_dir": "NNW",
									"pressure_mb": 1012,
									"pressure_in": 29.87,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 28,
									"cloud": 0,
									"feelslike_c": 25.2,
									"feelslike_f": 77.4,
									"windchill_c": 26,
									"windchill_f": 78.8,
									"heatindex_c": 25.2,
									"heatindex_f": 77.4,
									"dewpoint_c": 6.3,
									"dewpoint_f": 43.3,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 11.4,
									"gust_kph": 18.4,
									"uv": 1
								},
								{
									"time_epoch": 1636374600,
									"time": "2021-11-08 18:00",
									"temp_c": 23.6,
									"temp_f": 74.5,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 8.1,
									"wind_kph": 13,
									"wind_degree": 351,
									"wind_dir": "N",
									"pressure_mb": 1012,
									"pressure_in": 29.9,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 34,
									"cloud": 0,
									"feelslike_c": 24.3,
									"feelslike_f": 75.7,
									"windchill_c": 23.6,
									"windchill_f": 74.5,
									"heatindex_c": 24.3,
									"heatindex_f": 75.7,
									"dewpoint_c": 7,
									"dewpoint_f": 44.6,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 12.5,
									"gust_kph": 20.2,
									"uv": 1
								},
								{
									"time_epoch": 1636378200,
									"time": "2021-11-08 19:00",
									"temp_c": 22.5,
									"temp_f": 72.5,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 8.1,
									"wind_kph": 13,
									"wind_degree": 4,
									"wind_dir": "N",
									"pressure_mb": 1013,
									"pressure_in": 29.91,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 38,
									"cloud": 0,
									"feelslike_c": 24.1,
									"feelslike_f": 75.4,
									"windchill_c": 22.5,
									"windchill_f": 72.5,
									"heatindex_c": 24.1,
									"heatindex_f": 75.4,
									"dewpoint_c": 7.5,
									"dewpoint_f": 45.5,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 13.2,
									"gust_kph": 21.2,
									"uv": 1
								},
								{
									"time_epoch": 1636381800,
									"time": "2021-11-08 20:00",
									"temp_c": 19.2,
									"temp_f": 66.6,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 7.2,
									"wind_kph": 11.5,
									"wind_degree": 7,
									"wind_dir": "N",
									"pressure_mb": 1014,
									"pressure_in": 29.93,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 40,
									"cloud": 0,
									"feelslike_c": 19.2,
									"feelslike_f": 66.6,
									"windchill_c": 19.2,
									"windchill_f": 66.6,
									"heatindex_c": 19.2,
									"heatindex_f": 66.6,
									"dewpoint_c": 5.2,
									"dewpoint_f": 41.4,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 15,
									"gust_kph": 24.1,
									"uv": 1
								},
								{
									"time_epoch": 1636385400,
									"time": "2021-11-08 21:00",
									"temp_c": 18.9,
									"temp_f": 66,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 6.7,
									"wind_kph": 10.8,
									"wind_degree": 10,
									"wind_dir": "N",
									"pressure_mb": 1014,
									"pressure_in": 29.94,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 40,
									"cloud": 0,
									"feelslike_c": 18.9,
									"feelslike_f": 66,
									"windchill_c": 18.9,
									"windchill_f": 66,
									"heatindex_c": 18.9,
									"heatindex_f": 66,
									"dewpoint_c": 5,
									"dewpoint_f": 41,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 14.1,
									"gust_kph": 22.7,
									"uv": 1
								},
								{
									"time_epoch": 1636389000,
									"time": "2021-11-08 22:00",
									"temp_c": 18.5,
									"temp_f": 65.3,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 6.5,
									"wind_kph": 10.4,
									"wind_degree": 12,
									"wind_dir": "NNE",
									"pressure_mb": 1014,
									"pressure_in": 29.94,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 39,
									"cloud": 0,
									"feelslike_c": 18.5,
									"feelslike_f": 65.3,
									"windchill_c": 18.5,
									"windchill_f": 65.3,
									"heatindex_c": 18.5,
									"heatindex_f": 65.3,
									"dewpoint_c": 4.5,
									"dewpoint_f": 40.1,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 13.6,
									"gust_kph": 22,
									"uv": 1
								},
								{
									"time_epoch": 1636392600,
									"time": "2021-11-08 23:00",
									"temp_c": 17.9,
									"temp_f": 64.2,
									"is_day": 0,
									"condition": {
										"text": "Clear",
										"icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
										"code": 1000
									},
									"wind_mph": 6,
									"wind_kph": 9.7,
									"wind_degree": 10,
									"wind_dir": "N",
									"pressure_mb": 1014,
									"pressure_in": 29.93,
									"precip_mm": 0,
									"precip_in": 0,
									"humidity": 39,
									"cloud": 0,
									"feelslike_c": 17.9,
									"feelslike_f": 64.2,
									"windchill_c": 17.9,
									"windchill_f": 64.2,
									"heatindex_c": 17.9,
									"heatindex_f": 64.2,
									"dewpoint_c": 3.8,
									"dewpoint_f": 38.8,
									"will_it_rain": 0,
									"chance_of_rain": 0,
									"will_it_snow": 0,
									"chance_of_snow": 0,
									"vis_km": 10,
									"vis_miles": 6,
									"gust_mph": 12.8,
									"gust_kph": 20.5,
									"uv": 1
								}
							]
						}
					]
				}
			}
			)
	}
}